In [1]:
import os
import numpy as np
import pandas as pd

In [7]:
#loading csv with combined pearson_corr values of all tested models
df = pd.read_csv("pearson_correlation_summary.csv", sep=',', header=0)
print(df)

           Model        Fusion    DataTypes  PearsonCorrelation
0     DirectPred         early  mutationcnv            0.137811
1     DirectPred         early  mutationrna            0.403869
2     DirectPred  intermediate  mutationcnv            0.083667
3     DirectPred  intermediate  mutationrna            0.462277
4  supervisedvae         early  mutationcnv            0.180585
5  supervisedvae         early  mutationrna            0.362624
6  supervisedvae  intermediate  mutationcnv            0.230197
7  supervisedvae  intermediate  mutationrna            0.396525

In [17]:
#sorting the values from smaller to larger
df_sorted = df.sort_values(by="PearsonCorrelation", ascending=False)
print(df_sorted)

           Model        Fusion    DataTypes  PearsonCorrelation
3     DirectPred  intermediate  mutationrna            0.462277
1     DirectPred         early  mutationrna            0.403869
7  supervisedvae  intermediate  mutationrna            0.396525
5  supervisedvae         early  mutationrna            0.362624
6  supervisedvae  intermediate  mutationcnv            0.230197
4  supervisedvae         early  mutationcnv            0.180585
0     DirectPred         early  mutationcnv            0.137811
2     DirectPred  intermediate  mutationcnv            0.083667

The best model from this experiment is the one based on the DirectPred architecture, using the intermediate fusion type and mutation and rna datatypes. The pearson correlation value of 0.46 is closest to 1, with a moderate correlation.

## Exploring embeddings from best model

In [18]:
test_embed = pd.read_csv("results/DirectPred_intermediate_mutationrna.embeddings_test.csv", sep=',', header=0)

In [19]:
print(test_embed)

     Unnamed: 0        E0        E1        E2        E3        E4        E5  \
0     NCI-H2009 -0.144468 -0.184036 -0.151978  0.048703  0.131992 -0.437674
1     NCI-H1436  0.652658  1.178780 -1.110731 -0.431896  1.124072 -0.499846
2      NCI-H358 -0.137167 -0.146942 -0.166892  0.020068  0.143455 -0.405579
3    LB1047-RCC  0.122474  0.372651 -0.425167 -0.180018  0.611918 -0.104840
4         ECC12  0.066656  0.307513 -0.374528 -0.179993  0.528427 -0.087362
..          ...       ...       ...       ...       ...       ...       ...
604       OPM-2  0.024854  0.359905 -0.443556 -0.314340  0.320848 -0.187375
605      HAL-01  0.122474  0.372651 -0.425167 -0.180018  0.611918 -0.104840
606   NCI-H1573 -0.441233 -1.691825  0.454238  1.212614 -0.333922 -1.742271
607        Raji  0.066656  0.307513 -0.374528 -0.179993  0.528427 -0.087362
608       CaR-1  0.066656  0.307513 -0.374528 -0.179993  0.528427 -0.087362

           E6        E7        E8  ...      E176      E177      E178  \
0    0.519242 -0.144558  0.350859  ...  0.434669  0.191853 -0.037464
1   -0.204378 -0.356559  1.268652  ...  0.075880  0.542227 -0.254121
2    0.518484 -0.125958  0.367703  ...  0.321610  0.199817 -0.029651
3    0.560460 -0.064354  0.780839  ... -0.182251  0.171608 -0.096007
4    0.586476 -0.032514  0.716123  ... -0.220927  0.175867  0.173516
..        ...       ...       ...  ...       ...       ...       ...
604  0.338858  0.000071  0.603363  ... -0.122099 -0.919094  0.491148
605  0.560460 -0.064354  0.780839  ... -0.148017 -1.122180  0.351126
606  0.550053 -0.900578 -0.333832  ...  0.322784  0.317604 -0.171333
607  0.586476 -0.032514  0.716123  ... -0.084327 -1.383159  0.801017
608  0.586476 -0.032514  0.716123  ...  0.221056  0.241154 -0.201346

         E179      E180      E181      E182      E183      E184      E185
0    0.884829  0.572262 -0.225797 -0.080590 -0.062639 -0.514464  0.186325
1   -1.065599 -0.957406  0.231032 -1.017520 -1.175182 -0.143422 -0.563291
2    0.549400  0.343866 -0.183422 -0.266903  0.062224 -0.467801  0.226569
3    0.238156 -0.270070 -0.159202  0.029328 -0.088407 -0.005039 -0.241578
4   -0.631326 -0.519367  0.283337 -0.697890 -0.765437 -0.092307 -0.550310
..        ...       ...       ...       ...       ...       ...       ...
604 -1.401174  0.692579  0.756975 -0.987298  0.881132  0.783514 -0.151155
605 -2.610443  0.774838  1.072275 -3.037153  1.827391  1.781915 -0.304457
606  0.971982  0.684375 -0.619053 -0.207895 -0.181049 -0.591615 -0.055603
607 -2.377249  0.958206  1.193253 -2.110477  1.848302  1.607967  0.140085
608  0.939788  0.208613 -0.552544 -0.349881 -0.092179 -0.530682  0.095781

[609 rows x 187 columns]

In [20]:
train_embed = pd.read_csv("results/DirectPred_intermediate_mutationrna.embeddings_train.csv", sep=',', header=0)
train_embed.head(10)

,Unnamed: 0,E0,E1,E2,E3,E4,E5,E6,E7,E8,...,E176,E177,E178,E179,E180,E181,E182,E183,E184,E185
0,U-178MG,0.066656,0.307513,-0.374528,-0.179993,0.528427,-0.087362,0.586476,-0.032514,0.716123,...,-0.488879,0.380601,-0.740842,0.538547,-0.249521,0.090573,-0.158379,-0.512838,0.335099,-0.204804
1,NCI-H2009,-0.144468,-0.184036,-0.151978,0.048703,0.131992,-0.437674,0.519242,-0.144558,0.350859,...,0.127253,0.273249,-0.125381,0.715976,0.139463,-0.671711,-0.348234,-0.084479,-0.532655,-0.016553
2,NCI-H1436,0.256553,0.630512,-0.656094,-0.315628,0.663131,-0.266524,0.222805,-0.134023,0.869319,...,-0.247561,0.867741,-0.586910,-1.226197,-1.390865,-0.036334,-1.204755,-1.495619,-0.283937,-0.800549
3,HCC1195,0.215808,0.372906,-0.669316,-0.152383,0.387725,-0.842825,-0.173578,-0.381039,0.625910,...,0.154284,0.191230,-0.217489,0.874029,0.251780,-0.683150,-0.103762,-0.183961,-0.345540,0.265983
4,JHOS-4,0.066656,0.307513,-0.374528,-0.179993,0.528427,-0.087362,0.586476,-0.032514,0.716123,...,-0.016374,0.226729,0.025996,0.501033,-0.050095,-0.486600,-0.394352,0.199771,-0.285614,-0.057773
5,Hs 675.T,0.077039,0.045672,-0.282743,0.103738,0.579901,-0.354516,0.633661,-0.236575,0.674120,...,-0.452024,0.524779,-0.927677,0.635409,-0.413639,-0.101955,0.027671,-0.736299,0.523370,-0.229333
6,HuT 102,0.122474,0.372651,-0.425167,-0.180018,0.611918,-0.104840,0.560460,-0.064354,0.780839,...,-0.447471,-1.640552,0.790751,-2.378385,0.519830,1.229213,-2.253160,2.079098,1.225281,0.159613
7,NCI-H358,-0.068041,0.204270,-0.308098,-0.251043,0.251981,-0.101697,0.511307,0.050142,0.527189,...,0.200991,0.185811,-0.042271,0.608077,0.120326,-0.657104,-0.467462,0.120474,-0.550512,-0.024764
8,SIG-M5,-0.156088,-0.243077,-0.128240,0.094278,0.113749,-0.488758,0.520448,-0.174161,0.324048,...,-0.186501,-1.018332,0.607310,-1.689365,1.496995,0.722140,-1.818666,1.121824,1.413602,0.019661
9,ECC12,0.066656,0.307513,-0.374528,-0.179993,0.528427,-0.087362,0.586476,-0.032514,0.716123,...,-0.523719,0.801590,-0.171841,-0.735728,-1.172048,0.335004,-0.791113,-1.194049,-0.191831,-0.804041

## Feature importance for best model

In [23]:
feature_impc = pd.read_csv("results/DirectPred_intermediate_mutationrna.feature_importance.IntegratedGradients.csv", sep=',', header=0)
feature_impc.head(15)

,target_variable,target_class,target_class_label,layer,name,importance,explainer
0,Erlotinib,0,NaN,mutation,MSH6,0.000468,IntegratedGradients
1,Erlotinib,0,NaN,mutation,KRAS,0.002969,IntegratedGradients
2,Erlotinib,0,NaN,mutation,APC,0.002055,IntegratedGradients
3,Erlotinib,0,NaN,mutation,TP53,0.000730,IntegratedGradients
4,Erlotinib,0,NaN,mutation,JAK2,0.000562,IntegratedGradients
5,Erlotinib,0,NaN,mutation,BRAF,0.001836,IntegratedGradients
6,Erlotinib,0,NaN,mutation,KDM6A,0.000859,IntegratedGradients
7,Erlotinib,0,NaN,mutation,PTEN,0.001954,IntegratedGradients
8,Erlotinib,0,NaN,mutation,NF1,0.001589,IntegratedGradients
9,Erlotinib,0,NaN,mutation,BRCA2,0.001299,IntegratedGradients
10,Erlotinib,0,NaN,mutation,TSC1,0.001260,IntegratedGradients
11,Erlotinib,0,NaN,mutation,PIK3R1,0.000978,IntegratedGradients
12,Erlotinib,0,NaN,mutation,SMARCA4,0.002573,IntegratedGradients
13,Erlotinib,0,NaN,mutation,FBXW7,0.001984,IntegratedGradients
14,Erlotinib,0,NaN,mutation,CDH1,0.000472,IntegratedGradients

The top 10 markers are MSH6, KRAS, TP53, JAK2, BRAF, APC, KDM6A, PTEN, NF1, and BRCA2. 

KRAS, BRAF, JAK2, and TP53 are reported to be associated with Erlotinib.